# Generated by Django 3.2.25 on 2025-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20250614_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recur_frequency',
            field=models.CharField(choices=[('N', 'None'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='N', max_length=1),
        ),
    ]
